import JSZip from 'jszip';

interface FileToExport {
  name: string;
  path: string;
  content: string;
}

export async function exportProjectAsZip(
  files: FileToExport[],
  projectName: string = 'my-project'
): Promise<void> {
  const zip = new JSZip();

  files.forEach((file) => {
    zip.file(file.path, file.content);
  });

  const hasPackageJson = files.some(f => f.name === 'package.json');
  const hasIndexHtml = files.some(f => f.name === 'index.html');
  const hasIndexCss = files.some(f => f.path === 'src/index.css');
  const hasMainTsx = files.some(f => f.name === 'main.tsx' || f.name === 'main.jsx');

  if (!hasPackageJson) {
    zip.file('package.json', JSON.stringify({
    name: projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview'
    },
    dependencies: {
      react: '^18.3.1',
      'react-dom': '^18.3.1'
    },
    devDependencies: {
      '@types/react': '^18.3.11',
      '@types/react-dom': '^18.3.1',
      '@vitejs/plugin-react': '^4.3.0',
      typescript: '^5.6.0',
      vite: '^5.4.0',
      tailwindcss: '^3.4.0',
      autoprefixer: '^10.4.0',
      postcss: '^8.4.0'
    }
  }, null, 2));
  }

  if (!files.some(f => f.name === 'vite.config.ts' || f.name === 'vite.config.js')) {
    zip.file('vite.config.ts', `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})`);
  }

  if (!files.some(f => f.name === 'tsconfig.json')) {
    zip.file('tsconfig.json', JSON.stringify({
    compilerOptions: {
      target: 'ES2020',
      useDefineForClassFields: true,
      lib: ['ES2020', 'DOM', 'DOM.Iterable'],
      module: 'ESNext',
      skipLibCheck: true,
      moduleResolution: 'bundler',
      allowImportingTsExtensions: true,
      isolatedModules: true,
      moduleDetection: 'force',
      noEmit: true,
      jsx: 'react-jsx',
      strict: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noFallthroughCasesInSwitch: true,
      noUncheckedSideEffectImports: true
    },
    include: ['src']
  }, null, 2));
  }

  if (!files.some(f => f.name === 'tailwind.config.js' || f.name === 'tailwind.config.ts')) {
    zip.file('tailwind.config.js', `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`);
  }

  if (!files.some(f => f.name === 'postcss.config.js')) {
    zip.file('postcss.config.js', `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`);
  }

  if (!hasIndexHtml) {
    zip.file('index.html', `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`);
  }

  if (!hasIndexCss) {
    zip.file('src/index.css', `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}`);
  }

  if (!hasMainTsx) {
    zip.file('src/main.tsx', `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)`);
  }

  if (!files.some(f => f.name === 'README.md')) {
    const detectedLibraries = [];
    const allContent = files.map(f => f.content).join('\n');
    
    if (allContent.includes('framer-motion')) detectedLibraries.push('- Framer Motion (animations)');
    if (allContent.includes('lucide-react')) detectedLibraries.push('- Lucide React (icons)');
    if (allContent.includes('@tanstack/react-query')) detectedLibraries.push('- TanStack Query (data fetching)');
    if (allContent.includes('wouter')) detectedLibraries.push('- Wouter (routing)');
    if (allContent.includes('shadcn') || allContent.includes('@/components/ui')) detectedLibraries.push('- shadcn/ui (UI components)');
    
    const librariesSection = detectedLibraries.length > 0 
      ? `\n### Libraries\n${detectedLibraries.join('\n')}\n` 
      : '';
    
    zip.file('README.md', `# ${projectName}

This project was generated by **AI Code Agent** - an intelligent code generation tool.

## 🚀 Getting Started

### Prerequisites
- Node.js 18+ installed
- npm or yarn package manager

### Installation

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Copy environment variables:
\`\`\`bash
cp .env.example .env
\`\`\`

3. Run the development server:
\`\`\`bash
npm run dev
\`\`\`

4. Open [http://localhost:5173](http://localhost:5173) in your browser

## 📦 Build for Production

\`\`\`bash
npm run build
\`\`\`

The build output will be in the \`dist\` directory.

## 🛠 Tech Stack

- **React 18** - UI library
- **TypeScript** - Type safety
- **Vite** - Build tool & dev server
- **Tailwind CSS** - Utility-first CSS${librariesSection}

## 📁 Project Structure

\`\`\`
${projectName}/
├── src/
│   ├── components/    # React components
│   ├── App.tsx       # Main app component
│   └── main.tsx      # Entry point
├── public/           # Static assets
├── index.html        # HTML template
└── package.json      # Dependencies
\`\`\`

## 🔧 Available Scripts

- \`npm run dev\` - Start development server
- \`npm run build\` - Build for production
- \`npm run preview\` - Preview production build

## 📝 License

MIT

---

Generated with ❤️ by AI Code Agent
`);
  }

  if (!files.some(f => f.name === '.gitignore')) {
    zip.file('.gitignore', `# Dependencies
node_modules
/.pnp
.pnp.js

# Testing
/coverage

# Production
/build
/dist

# Misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# Editor
.vscode/*
!.vscode/extensions.json
.idea
*.swp
*.swo
*~

# OS
Thumbs.db
`);
  }

  if (!files.some(f => f.name === '.env.example')) {
    zip.file('.env.example', `# Environment Variables Example
# Copy this file to .env and fill in your values

# API Keys
# VITE_API_KEY=your_api_key_here

# API URL (if using external API)
# VITE_API_URL=http://localhost:3000/api

# Other configuration
# VITE_APP_NAME=${projectName}
`);
  }

  if (!files.some(f => f.name === 'Dockerfile')) {
    zip.file('Dockerfile', `FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`);
  }

  if (!files.some(f => f.name === 'docker-compose.yml')) {
    zip.file('docker-compose.yml', `version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
`);
  }

  const blob = await zip.generateAsync({ type: 'blob' });

  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${projectName.toLowerCase().replace(/\s+/g, '-')}.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}
